#!/bin/bash
## Usage: telelog [flags] [content]
### Designed to use with /bin/bash shell.
### Send content to a Telegram channel from the command line.

args=("$@")
shell="bash"
i=0

show_help() {
    echo ""
    echo "Usage: telelog [flags] [content]"
    echo "Flags: "
    echo "       --message, -m: Send a message to the channel."
    echo "       --file, -f: Send a file to the channel."
    echo "       --help, -h: Show this help message."
    echo ""
    echo "Example: telelog --message 'Hello, World!'"
    echo "Example: telelog --file /path/to/file"
    echo "Example: telelog --message 'Hello, World!' --file /path/to/file"
    echo ""
}

if [ ${#args[@]} -eq 0 ]; then
    show_help
    exit 1
fi

source ~/.bashrc

if [ -z "$chat_id" ]; then
    read -p "Enter chat_id: " std_chat_id
    if [[ "$shell" == "bash" ]]; then
        echo "export chat_id=$std_chat_id" >> ~/.bashrc
    fi
fi

if [ -z "$token" ]; then
    read -p "Enter token: " std_token
    if [[ "$shell" == "bash" ]]; then
        echo "export token=$std_token" >> ~/.bashrc
    fi
fi

for arg in "${args[@]}"; do
    server_name=$(hostname)
    date=$(date +%F)

    if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
        show_help
    fi

    if [ "$arg" == "--message" ] || [ "$arg" == "-m" ]; then
        if [ $((i + 1)) -lt ${#args[@]} ]; then
            message=${args[$((i + 1))]}
            echo "Message: $message"
            curl -X POST -H "content-type: application/json" -d "{\"chat_id\": \"$chat_id\", \"text\": \"Date: $date\nMessage: $message\nServer: $server_name\", \"disable_notification\": true}" https://api.telegram.org/bot"$token"/sendMessage
        else
            echo "Error: --message flag provided but no message found after it."
        fi
    fi

    if [ "$arg" == "--file" ] || [ "$arg" == "-f" ]; then
        if [ $((i + 1)) -lt ${#args[@]} ]; then
            file=${args[$((i + 1))]}
            echo "File: $file"
            curl -X POST -H "content-type: multipart/form-data" -F document=@"$file" -F chat_id="$chat_id" https://api.telegram.org/bot"$token"/sendDocument
        else
            echo "Error: --file flag provided but no file found after it."
        fi
    fi

    i=$((i + 1))
done
