name: test and publish

on:
  workflow_dispatch:
  push:
    branches: [ "develop", "master" ]
    paths:
      - 'lib/**'
      - '.github/workflows/release.yml'
  pull_request:
    branches: [ "develop", "master" ]
    paths:
      - 'lib/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:

  linter:
    uses: jd-apprentice/jd-workflows/.github/workflows/linter.yml@main
    with:
      name: linter
      runs_on: ubuntu-latest

  test:
    runs-on: ubuntu-latest
    needs: [linter]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        run: make pipeline

  release:
    uses: jd-apprentice/jd-workflows/.github/workflows/release.yml@main
    needs: [test]
    if: github.ref == 'refs/heads/master'
    with:
      name: test and publish
      runs_on: ubuntu-latest
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}